### PR TITLE
Useful functions for fitting

### PR DESCRIPTION
**Pull request by gonzaponte**
This PR adds multiple functions used in the Kr notebooks that can be helpful elsewhere:

- Seed estimation for gaussian and exponential fits.
- Safe computation of relative errors.
- Quick (and the simplest) fit to a gaussian distribution.
- Lifetime-style exponential fit.
- 1-D and 2-D data binning with gaussian and exponential fits.

### CODE REVIEW

**Comment by jahernando** [comment]
The functions are almost self-documented, but please add an extra comment on the headers to indicate what are their purposes.

It seems to me that there is still one function missing. The function that computes the lifetime, by fitting an exponential, but using as points [(z, ene)] the result of applying the fit to a gaussian into z-ranges. Then you can either compute the lifetime or lifetime map using the profile of the result or the gaussian fits into z-slices. Do you agree?

**Comment by gonzaponte** [comment]
> The functions are almost self-documented, but please add an extra comment on the headers to indicate what are their purposes.

Ok.


> It seems to me that there is still one function missing. The function that computes the lifetime, by fitting an exponential, but using as points [(z, ene)] the result of applying the fit to a gaussian into z-ranges.  Then you can either compute the lifetime or lifetime map using the profile of the result of the gaussian fits into z-slices. Do you agree?

I am not completely sure what you mean, but
- You can't use gaussian fits for the lifetime map, there is not that much statistics.
- I think that

```
do_z_slices
fit_to_expo
```

is more readable than

```
fit_to_expo_the_result_of_doing_z_slices
```

**Comment by jahernando** [comment]
In fact, if your distribution is gaussian, there is little difference in doing the fit to a gaussian or to compute the mean and std of the distribution. If there is no stats for one, there is no stats for the other.

But I agree with you, that is more readable if one applies the function one after the other, then the reader can follow better what the is done. 

Please add the comments to approve the PR.

**Comment by jahernando** [comment]
Approved!

**Review by jahernando — APPROVED** [review]
Approved

**Pull request merged**
